version: '3.1'

services:
  erpnext:
    image: pipech/erpnext-docker-debian:v13-py3-latest
    restart: always
    user: root
    restart: always
    ports:
    - 8000:8000 #webserver_port
    - 9000:9000 #socketio_port
    - 6787:6787 #file_watcher_port
    - 3306:3306 # mysql
